name: Opdex-Database
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  location: 'Central US'
  azureSubscription: 'sub-opdex-dev'
  ARTIFACT_NAME: platform-db
  artifactName: ReleaseArtifact
  releaseTemplate: 'azure-pipelines.release.yml'

stages:
- stage: CI
  displayName: 'Continuous Integration'
  jobs:
  - job: Build
    steps:
    - task: PublishBuildArtifacts@1 
      displayName: 'Publish artifact in pipeline' 
      inputs: 
        PathtoPublish: '$(Build.SourcesDirectory)/deploy.sql'
        ArtifactName: 'database'
        publishLocation: 'Container' 

- stage: DEV
  displayName: 'Release to devnet (Azure)'
  dependsOn: CI
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main')) # Don't run deployment for PRs against the branch.
  jobs:
  - template: ${{ variables.releaseTemplate }}
    parameters:
      environment: 'dev'

- stage: TEST
  displayName: 'Release to testnet (Azure)'
  dependsOn: DEV
  jobs:
  - template: ${{ variables.releaseTemplate }}
    parameters:
      environment: 'test'

- stage: MAIN
  displayName: 'Release to mainnet (Azure)'
  dependsOn: TEST
  jobs:
  - template: ${{ variables.releaseTemplate }}
    parameters:
      environment: 'main'
