parameters:
- name: environment
  type: string

jobs:
  - deployment: ${{ parameters.environment }}
    displayName: 'Deploy Resources'
    variables:
      - group: ${{ parameters.environment }} # points to variable group in Azure DevOps
    environment: ${{ parameters.environment }} # points to environments in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          # - checkout: self # Check if we need to perform a checkout, we download the artifact.
          - task: AzureMysqlDeployment@1
            inputs:
              azureSubscription: $(azureSubscription) 
              #ServerName: 'mdb-opdex-${{ parameters.environment }}.mariadb.database.azure.com'
              ServerName: 'mdb-opdex-dev'
              # SqlUsername: 'opdex@mdb-opdex-${{ parameters.environment }}'
              SqlUsername: 'opdex@mdb-opdex-dev'
              SqlPassword: '$(sqlpassword)'
              TaskNameSelector: 'SqlTaskFile'
              DatabaseName: 'platform'
              SqlFile: $(Build.SourcesDirectory)/deploy.sql
              IpDetectionMethod: 'AutoDetect'
